version: '3.7'
services:
    back:
        image: node:latest
        volumes:
            - .:/opt/app
        command: >
            sh -c "npm install && npm run bootstrap && npm run build"
        restart: unless-stopped
    front:
        depends_on:
            - back
        image: nginx:latest
        volumes:
            - ./packages/front/dist:/usr/share/nginx/html
        restart: unless-stopped
