version: "3"
services:
    back:
        image: node:latest
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        command: >
            sh -c "cd /usr/app &&
                npm install --quiet &&
                npm run bootstrap && npm run build"
        restart: unless-stopped
    front:
        depends_on:
            - back
        image: nginx:latest
        volumes:
            - ./packages/front/dist:/usr/share/nginx/html
        restart: unless-stopped
