version: "3"
services:
    amqp:
        image: rabbitmq:latest
        ports:
            - 5672:5672
        restart: always
    back:
        depends_on:
            - amqp
        image: node:latest
        volumes:
            - .:/usr/app
        command: >
            sh -c "cd /usr/app &&
                npm install &&
                npm run bootstrap &&
                npm run build &&
                npm run start:prod"
        restart: unless-stopped
    front:
        depends_on:
            - back
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./packages/front/dist:/usr/share/nginx/html
        restart: unless-stopped
