version: "3"
services:
    amqp:
        image: rabbitmq:latest
        ports:
            - 5672:5672
        restart: always
    sensor:
        depends_on:
            - amqp
        image: node:latest
        volumes:
            - ./packages/sensor-service:/usr/app
        command: >
            sh -c "cd /usr/app &&
                npm install &&
                npm run build &&
                npm run start:prod"
        restart: unless-stopped
    auth:
        depends_on:
            - amqp
        image: node:latest
        volumes:
            - ./packages/auth-service:/usr/app
        command: >
            sh -c "cd /usr/app &&
                npm install &&
                npm run build &&
                npm run start:prod"
        restart: unless-stopped
    gateway:
        depends_on:
            - amqp
            - auth
        image: node:latest
        volumes:
            - ./packages/gateway-service:/usr/app
        command: >
            sh -c "cd /usr/app &&
                npm install &&
                npm run build &&
                npm run start:prod"
        restart: unless-stopped
    front:
        depends_on:
            - gateway
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./packages/front/dist:/usr/share/nginx/html
        restart: unless-stopped
