version: "3"
services:
    amqp:
        image: rabbitmq:latest
        restart: always

    auth:
        depends_on:
            - amqp
        image: node:latest
        volumes:
            - ./packages/auth-service:/usr/app
        command: >
            sh -c "cd /usr/app &&
                npm ci &&
                npm run build &&
                npm run start:prod"
        restart: always

    sensor:
        depends_on:
            - amqp
        image: node:latest
        volumes:
            - ./packages/sensor-service:/usr/app
        command: >
            sh -c "cd /usr/app &&
                npm ci &&
                npm run build &&
                npm run start:prod"
        restart: always

    graphql:
        depends_on:
            - amqp
            - sensor
        image: node:latest
        volumes:
            - ./packages/gql-service:/usr/app
        command: >
            sh -c "cd /usr/app &&
                npm ci &&
                npm run build &&
                npm run start:prod"
        restart: always

    gateway:
        depends_on:
            - amqp
            - auth
            - graphql
        image: node:latest
        volumes:
            - ./packages/gateway-service:/usr/app
        command: >
            sh -c "cd /usr/app &&
                npm ci &&
                npm run build &&
                npm run start:prod"
        restart: always

    front:
        depends_on:
            - gateway
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./packages/front/dist:/usr/share/nginx/html
        restart: always
