version: "3"
services:
    back:
        image: node:latest
        volumes:
            - .:/usr/app
        command: >
            sh -c "cd /usr/app &&
                npm install &&
                npm run bootstrap &&
                npm run build &&
                npm run start:prod"
        restart: unless-stopped
    front:
        depends_on:
            - back
        image: nginx:latest
        volumes:
            - ./packages/front/dist:/usr/share/nginx/html
        restart: unless-stopped
