version: '3'
services:
    amqp:
        image: rabbitmq:latest
        restart: always

    back:
        depends_on:
            - amqp
        image: node:latest
        volumes:
            - ./packages/back:/usr/app
        ports:
            - 3000:3000
        command: >
            sh -c "cd /usr/app/ &&
                npm ci &&
                npm run build &&
                npm run start:prod"
        restart: always
    # front:
    #     depends_on:
    #         - gateway
    #     image: nginx:latest
    #     ports:
    #         - 80:80
    #         - 443:443
    #     volumes:
    #         - ./packages/front/dist:/usr/share/nginx/html
    #     restart: always
